image: maven:latest

cache:
  paths:
    - $HOME/.m2/
    - target/

variables:
  CI_DEBUG_TRACE: "true"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-s ./resources/deployment/mvn-settings.xml --batch-mode"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS install

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy