image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-s ./resources/deployment/mvn-settings.xml --batch-mode"

build:
  stage: build
  script:
    - echo $BINTRAY_USERNAME
    - mvn $MAVEN_CLI_OPTS install

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy